# Site settings
title:         Anne Melody
description:   Travels and personal experiences of a human from the sunny island of Cebu.
email:         annemelodysy@gmail.com
url:           http://annemelody.com
base.url:
site.url:      annemelody.com
paginate:      240
paginate_path: "/page:num/"
sass:
  style:       compressed
sass_dir:      _sass
markdown:      kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
future:        true
repository:    annemelodysy/annemelodysy.github.io
