# Site settings
title:         Anne Melody
description:   Annemelody.com are stories about the travels and personal experiences of a human from the sunny island of Cebu.
email:         annemelodysy@gmail.com
url:           http://annemelody.com
base.url:      journal
site.url:      annemelody.com
paginate:      240
paginate_path: "/page:num/"
sass:
  style:       compressed
markdown:      kramdown
